name: Cleanup Drinks Content

on:
  workflow_dispatch:
    inputs:
      write:
        description: "Apply changes (true) or dry run (false)"
        required: true
        default: "false"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run cleanup script
        run: |
          if [ "${{ github.event.inputs.write }}" = "true" ]; then
            node scripts/cleanup-drinks.js --write
          else
            node scripts/cleanup-drinks.js
          fi

      - name: Commit changes (if write)
        if: ${{ github.event.inputs.write == 'true' }}
        run: |
            if [ -n "$(git status --porcelain)" ]; then
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git add .
              git commit -m "chore: cleanup drinks content & legacy files"
              git push
            else
              echo "No changes to commit."
            fi
