name: Extract Legacy Content

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Overwrite existing slugs (true/false)"
        required: false
        default: "false"
      dry:
        description: "Dry run (true/false)"
        required: false
        default: "false"

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Run extractor
        run: |
          FORCE=${{ github.event.inputs.force }} DRY=${{ github.event.inputs.dry }} npm run extract-legacy
      - name: Commit changes
        if: ${{ github.event.inputs.dry != 'true' }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add src/content
            git commit -m "chore: extract legacy content (force=${{ github.event.inputs.force }})"
            git push
          else
            echo "No new content generated."
          fi
